# This is a config for E2B sandbox template.
# You can use template ID (46t4gsd4m8kmhbikae1v) or template name (kryft-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("kryft-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("kryft-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('kryft-nextjs-test')

team_id = "10b1a248-8caf-4326-95c2-0599c1713e5d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "kryft-nextjs-test"
template_id = "46t4gsd4m8kmhbikae1v"
